
---------------------------------------------------------
DROP TABLE LOTTO;

CREATE TABLE LOTTO(
     LOTTO_NO NUMBER(10) 
    ,LOTTO_ROUND NUMBER(10) 
    ,LOTTO_MODE NUMBER(10)
    ,MEMBER_NO NUMBER(10)
    ,LOTTO_WINNING NUMBER(10)
    ,LOTTO_1ST NUMBER(10)
    ,LOTTO_2ND NUMBER(10)
    ,LOTTO_3RD NUMBER(10)
    ,LOTTO_SEL_NO VARCHAR2(100) 
    ,LOTTO_START_DATE VARCHAR2(50)
    ,LOTTO_END_DATE VARCHAR2(50)
    ,LOTTO_CREDATE DATE
    ,CONSTRAINT LOTTO_NO_PK PRIMARY KEY (LOTTO_NO)
);

DROP SEQUENCE LOTTO_NO_SEQ;

CREATE SEQUENCE LOTTO_NO_SEQ
INCREMENT BY 1
START WITH 1; 

SELECT *
FROM MEMBER;

SELECT *
FROM LOTTO;

INSERT INTO LOTTO(LOTTO_NO, LOTTO_ROUND, LOTTO_MODE, MEMBER_NO, LOTTO_SEL_NO, LOTTO_START_DATE, LOTTO_END_DATE ,LOTTO_CREDATE)
VALUES(LOTTO_NO_SEQ.NEXTVAL, 1, 1, 1, '[2, 18, 20, 22, 35, 39]', '2024-10-21', '2024-10-30', SYSDATE);
--
--INSERT INTO LOTTO(LOTTO_NO, LOTTO_ROUND, LOTTO_MODE, MEMBER_NO, LOTTO_SEL_NO, LOTTO_CREDATE)
--VALUES(LOTTO_NO_SEQ.NEXTVAL, 1, 0, 2, '[2, 18, 20, 22, 35, 36]', SYSDATE);

SELECT LOTTO_NO, LOTTO_ROUND, 
    MEMBER_NO, LOTTO_SEL_NO, LOTTO_START_DATE, LOTTO_END_DATE 
FROM LOTTO
WHERE LOTTO_START_DATE <= TO_DATE('2024-10-25', 'YYYY-MM-DD')
  AND LOTTO_END_DATE >= TO_DATE('2024-10-25', 'YYYY-MM-DD')
  AND LOTTO_MODE = 1;
  
select *
from lotto;
  
  
SELECT LOTTO_NO, LOTTO_ROUND, 
MEMBER_NO, LOTTO_SEL_NO, LOTTO_START_DATE, LOTTO_END_DATE 
FROM LOTTO
WHERE LOTTO_START_DATE <= TRUNC(SYSDATE)
AND LOTTO_END_DATE >= TRUNC(SYSDATE)
AND LOTTO_MODE = 1;
  
commit;
----------------------------------------------------------------------------
SELECT *
FROM BOARD;

SELECT MEMBER_NO
FROM (
    SELECT MEMBER_NO
    FROM BOARD
    ORDER BY DBMS_RANDOM.VALUE
)
WHERE ROWNUM <= 1;
  