DROP TABLE DRAWING;

CREATE TABLE DRAWING(
     DRAWING_NO NUMBER(20)
    ,DRAWING_ROUND NUMBER(20)
    ,MEMBER_NO NUMBER(20)
    ,DRAWING_PERSONNEL NUMBER(20)
    ,DRAWING_POINT NUMBER(20)
    ,DRAWING_MEMBER_NO VARCHAR2(10)
    ,DRAWING_MEMBER_ID VARCHAR2(200)
    ,DRAWING_MEMBER_NAME VARCHAR2(200)
    ,DRAWING_START_DATE VARCHAR2(100)
    ,DRAWING_END_DATE VARCHAR2(100)
    ,DRAWING_CREDATE DATE
    ,CONSTRAINT DRAWING_NO PRIMARY KEY (DRAWING_NO)
);

DROP SEQUENCE DRAWING_NO_SEQ;

CREATE SEQUENCE DRAWING_NO_SEQ
INCREMENT BY 1
START WITH 1;


SELECT *
FROM DRAWING;

SELECT MEMBER_NO, MEMBER_NAME
FROM (
    SELECT DISTINCT M.MEMBER_NO, M.MEMBER_NAME
    FROM BOARD B
    JOIN MEMBER M ON B.MEMBER_NO = M.MEMBER_NO
    WHERE M.AUTHORITY != 1
    AND B.BOARD_CREDATE > TO_DATE('2024-10-30', 'YYYY-MM-DD')
    ORDER BY DBMS_RANDOM.VALUE
)
WHERE ROWNUM <= 3;

commit;

SELECT D.DRAWING_NO, D.DRAWING_ROUND, D.MEMBER_NO, D.DRAWING_MEMBER_NO, D.DRAWING_MEMBER_NAME, 
       D.DRAWING_START_DATE, D.DRAWING_END_DATE, D.DRAWING_CREDATE, 
       M.MEMBER_NAME
FROM DRAWING D
JOIN MEMBER M ON D.MEMBER_NO = M.MEMBER_NO
ORDER BY D.DRAWING_NO DESC;

UPDATE DRAWING
SET MEMBER_NO = 1
WHERE DRAWING_NO = 1;