DROP TABLE DRAWING;

CREATE TABLE DRAWING(
     DRAWING_NO NUMBER(20)
    ,DRAWING_ROUND NUMBER(20)
    ,MEMBER_NO NUMBER(20)
    ,DRAWING_PERSONNEL NUMBER(20)
    ,DRAWING_POINT NUMBER(20)
    ,DRAWING_MEMBER_NO VARCHAR2(10)
    ,DRAWING_MEMBER_ID VARCHAR2(200)
    ,DRAWING_MEMBER_NAME VARCHAR2(200)
    ,DRAWING_START_DATE VARCHAR2(100)
    ,DRAWING_END_DATE VARCHAR2(100)
    ,DRAWING_CREDATE DATE
    ,CONSTRAINT DRAWING_NO PRIMARY KEY (DRAWING_NO)
);

DROP SEQUENCE DRAWING_NO_SEQ;

CREATE SEQUENCE DRAWING_NO_SEQ
INCREMENT BY 1
START WITH 1;


SELECT *
FROM DRAWING;



commit;


