
DROP TABLE EVENT;

CREATE TABLE EVENT(
     EVENT_NO NUMBER(10)
    ,EVENT_CATEGORY_NO NUMBER(10)
    ,EVENT_HIDE_SHOW NUMBER(10)
    ,EVENT_CREADATE DATE 
    ,EVENT_UPDATE DATE 
    ,CONSTRAINT EVENT_NO_PK PRIMARY KEY (EVENT_NO)
);

DROP SEQUENCE EVENT_NO_SEQ;

CREATE SEQUENCE EVENT_NO_SEQ
INCREMENT BY 1
START WITH 1; 

INSERT INTO EVENT(EVENT_NO, EVENT_CATEGORY_NO, EVENT_HIDE_SHOW, EVENT_CREADATE, EVENT_UPDATE)
VALUES(EVENT_NO_SEQ.NEXTVAL, 1, 1, SYSDATE, SYSDATE);

INSERT INTO EVENT(EVENT_NO, EVENT_CATEGORY_NO, EVENT_HIDE_SHOW, EVENT_CREADATE, EVENT_UPDATE)
VALUES(EVENT_NO_SEQ.NEXTVAL, 2, 1, SYSDATE, SYSDATE);

SELECT EVENT_NO, EVENT_CATEGORY_NO, EVENT_HIDE_SHOW, EVENT_CREADATE, EVENT_UPDATE
FROM EVENT;

UPDATE EVENT
SET EVENT_HIDE_SHOW = 1, EVENT_UPDATE = SYSDATE
WHERE EVENT_CATEGORY_NO = 1;

UPDATE EVENT
SET EVENT_HIDE_SHOW = 0, EVENT_UPDATE = SYSDATE
WHERE EVENT_CATEGORY_NO = 2;

select *
from event;

COMMIT;