--MEMBER DML

DROP TABLE EVENT;

CREATE TABLE EVENT(
     EVENT_NO NUMBER(10)
    ,EVENT_LOTTO NUMBER(10)
    ,EVENT_DRAWING NUMBER(10)
    ,EVENT_LOTTO_UPDATE DATE 
    ,EVENT_DRAWING_UPDATE DATE 
    ,CONSTRAINT EVENT_NO_PK PRIMARY KEY (EVENT_NO)
);

DROP SEQUENCE EVENT_NO_SEQ;

CREATE SEQUENCE EVENT_NO_SEQ
INCREMENT BY 1
START WITH 1; 

INSERT INTO EVENT(EVENT_NO, EVENT_LOTTO, EVENT_DRAWING, EVENT_LOTTO_UPDATE, EVENT_DRAWING_UPDATE)
VALUES(EVENT_NO_SEQ.NEXTVAL, 1, 1, SYSDATE, SYSDATE);

SELECT EVENT_NO, EVENT_LOTTO, EVENT_DRAWING, EVENT_LOTTO_UPDATE, EVENT_DRAWING_UPDATE
FROM EVENT;

COMMIT;

SELECT *
FROM EVENT;

SELECT *
FROM MEMBER;

SELECT *
FROM MEMBER_E_MONEY;


