--MEMBER_SHOPPING_CART--DML

DROP TABLE MEMBER_SHOPPING_CART;

CREATE TABLE MEMBER_SHOPPING_CART(
     MEMBER_SHOPPING_CART_NO NUMBER(10)
    ,MEMBER_NO NUMBER(10) 
    ,COURSE_NO NUMBER(10)
    ,CONSTRAINT MEMBER_SHOPPING_CART_NO_PK PRIMARY KEY (MEMBER_SHOPPING_CART_NO)
    ,CONSTRAINT SC_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
    ,CONSTRAINT SC_COURSE_NO_FK FOREIGN KEY (COURSE_NO) REFERENCES COURSE_LIST(COURSE_NO)
);
    
DROP SEQUENCE MEMBER_SHOPPING_CART_NO_SEQ;

CREATE SEQUENCE MEMBER_SHOPPING_CART_NO_SEQ
INCREMENT BY 1
START WITH 1;

COMMIT;
