--FREE_CONTENT_BOARD DML

DROP TABLE BOARD;

CREATE TABLE BOARD(
     BOARD_NO NUMBER(20)
    ,MEMBER_NO NUMBER(10)
    ,BOARD_TITLE VARCHAR2(1000)
    ,BOARD_CONTENT VARCHAR2(3000)
    ,BOARD_IMG VARCHAR2(2000)
    ,BOARD_CREDATE DATE DEFAULT SYSDATE
    ,BOARD_UPDATE DATE DEFAULT SYSDATE
    ,CONSTRAINT BOARD_NO_PK PRIMARY KEY (BOARD_NO)
    ,CONSTRAINT B_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)   
);

DROP SEQUENCE BOARD_NO_SEQ;

CREATE SEQUENCE BOARD_NO_SEQ
INCREMENT BY 1
START WITH 1;




commit;