--ADMIN NOTICE DML

DROP TABLE NOTICE;

CREATE TABLE NOTICE(
     NOTICE_NO NUMBER(10)
    ,MEMBER_NO NUMBER(10)
    ,NOTICE_TITLE VARCHAR2(200)
    ,NOTICE_CONTENT VARCHAR2(1000)
    ,NOTICE_IMG VARCHAR2(2000)
    ,NOTICE_CREDATE DATE DEFAULT SYSDATE
    ,NOTICE_UPDATE DATE DEFAULT SYSDATE
    ,CONSTRAINT NOTICE_NO_PK PRIMARY KEY (NOTICE_NO)
    ,CONSTRAINT N_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

DROP SEQUENCE NOTICE_NO_SEQ;

CREATE SEQUENCE NOTICE_NO_SEQ
INCREMENT BY 1
START WITH 1;





SELECT *
FROM NOTICE;

COMMIT;