--CREATE USER TEST IDENTIFIED BY 1;
--GRANT CONNECT, RESOURCE, DBA TO TEST;

--ADMIN DML

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
     CUSTOMER_NO NUMBER(10)
    ,MEMBER_Q_NO NUMBER(10)
    ,MEMBER_A_NO NUMBER(10)
    ,CUSTOMER_TITLE VARCHAR2(500)
    ,CUSTOMER_QUE VARCHAR2(1000)
    ,CUSTOMER_ANS VARCHAR2(1000)
    ,CUSTOMER_Q_CREDATE DATE
    ,CUSTOMER_A_CREDATE DATE
    ,CUSTOMER_CHECK VARCHAR2(100) DEFAULT '답변준비중'
    ,CONSTRAINT CUSTOMER_NO PRIMARY KEY (CUSTOMER_NO)
);

DROP SEQUENCE CUSTOMER_NO_SEQ;

CREATE SEQUENCE CUSTOMER_NO_SEQ
INCREMENT BY 1
START WITH 1;

SELECT *
FROM CUSTOMER;

COMMIT;



