--FREE_CONTENT_COMMENT DML

DROP TABLE COMMENTS;

CREATE TABLE COMMENTS (
     COMMENTS_NO NUMBER(20),
     BOARD_NO NUMBER(20),
     MEMBER_NO NUMBER(10),
     COMMENTS_CONTENT VARCHAR2(1000),
     COMMENTS_CREDATE DATE DEFAULT SYSDATE,
     COMMENTS_UPDATE DATE DEFAULT SYSDATE,
     CONSTRAINT COMMENTS_NO_PK PRIMARY KEY (COMMENTS_NO),
     CONSTRAINT C_BOARD_NO_FK FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
     CONSTRAINT C_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

DROP SEQUENCE COMMENTS_NO_SEQ;

CREATE SEQUENCE COMMENTS_NO_SEQ
INCREMENT BY 1
START WITH 1;

SELECT *
FROM BOARD;

SELECT *
FROM MEMBER;

SELECT *
FROM COMMENTS;


SELECT C.COMMENTS_NO, C.MEMBER_NO, C.BOARD_NO, C.COMMENTS_CONTENT, 
   C.COMMENTS_CREDATE, C.COMMENTS_UPDATE, M.MEMBER_NAME 
FROM COMMENTS C
JOIN MEMBER M ON C.MEMBER_NO = M.MEMBER_NO 
WHERE BOARD_NO = 6
ORDER BY C.COMMENTS_NO DESC;

COMMIT;

--ALTER TABLE COMMENTS
--DROP CONSTRAINT C_BOARD_NO_FK;
--
--ALTER TABLE COMMENTS
--DROP CONSTRAINT C_MEMBER_NO_FK;
--
--
--ALTER TABLE COMMENTS
--ADD CONSTRAINT C_BOARD_NO_FK FOREIGN KEY (BOARD_NO) 
--REFERENCES BOARD (BOARD_NO) ON DELETE CASCADE;
--
--ALTER TABLE COMMENTS
--ADD CONSTRAINT C_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) 
--REFERENCES MEMBER (MEMBER_NO) ON DELETE CASCADE;
