--FREE_CONTENT_COMMENT DML

DROP TABLE COMMENTS;

CREATE TABLE COMMENTS (
     COMMENTS_NO NUMBER(20),
     BOARD_NO NUMBER(20),
     MEMBER_NO NUMBER(10),
     COMMENTS_CONTENT VARCHAR2(1000),
     COMMENTS_CREDATE DATE DEFAULT SYSDATE,
     COMMENTS_UPDATE DATE DEFAULT SYSDATE,
     CONSTRAINT COMMENTS_NO_PK PRIMARY KEY (COMMENTS_NO),
     CONSTRAINT C_BOARD_NO_FK FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
     CONSTRAINT C_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

DROP SEQUENCE COMMENTS_NO_SEQ;

CREATE SEQUENCE COMMENTS_NO_SEQ
INCREMENT BY 1
START WITH 1;



SELECT *
FROM COMMENTS;



COMMIT;
