--CATEGORY DML

DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
     CATEGORY_NO NUMBER(10)
    ,CATEGORY_NAME VARCHAR2(50) NOT NULL
    ,CONSTRAINT CATEGORY_NO_PK PRIMARY KEY (CATEGORY_NO)    
);

DROP SEQUENCE CATEGORY_NO_SEQ;

CREATE SEQUENCE CATEGORY_NO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO category(CATEGORY_NO, CATEGORY_NAME)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, '수영');

INSERT INTO category(CATEGORY_NO, CATEGORY_NAME)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, '테니스');

INSERT INTO category(CATEGORY_NO, CATEGORY_NAME)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, '탁구');

INSERT INTO category(CATEGORY_NO, CATEGORY_NAME)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, '골프');

INSERT INTO category(CATEGORY_NO, CATEGORY_NAME)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, '요가');

SELECT *
FROM CATEGORY;

COMMIT;
