--COURSE_LIST_DAY DML

DROP TABLE COURSE_LIST_DAY;

CREATE TABLE COURSE_LIST_DAY(
    COURSE_LIST_DAY_NO NUMBER(10),
    COURSE_NO NUMBER(10),
    COURSE_DAY_OF_THE_WEEK NUMBER(10),
    CONSTRAINT COURSE_LIST_DAY_NO_PK PRIMARY KEY (COURSE_LIST_DAY_NO),
    CONSTRAINT C_C_COURSE_NO_FK FOREIGN KEY (COURSE_NO) REFERENCES COURSE_LIST(COURSE_NO)
);

DROP SEQUENCE COURSE_LIST_DAY_NO_SEQ;

CREATE SEQUENCE COURSE_LIST_DAY_NO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO COURSE_LIST_DAY(COURSE_LIST_DAY_NO, COURSE_NO, COURSE_DAY_OF_THE_WEEK)
VALUES (COURSE_LIST_DAY_NO_SEQ.NEXTVAL, 3, 3);

SELECT *
FROM COURSE_LIST_DAY;

desc COURSE_LIST_DAY;
desc COURSE_LIST;

select *
from COURSE_LIST CL, COURSE_LIST_DAY CLD
where CL.COURSE_NO = CLD.COURSE_NO
AND CL.COURSE_NO = 5;

SELECT *
FROM COURSE_LIST
WHERE COURSE_NO = 5;

SELECT *
FROM COURSE_LIST_DAY
WHERE COURSE_NO = 5;

SELECT *
FROM COURSE_LIST_DAY
WHERE COURSE_NO = 5;




COMMIT;