DROP TABLE MEMBER_E_MONEY;

CREATE TABLE MEMBER_E_MONEY(
    MEMBER_NO NUMBER(10),
    MEMBER_E_MONEY_NO NUMBER(10),
    MEMBER_E_MONEY_PLUS NUMBER(30) DEFAULT 0,
    MEMBER_E_MONEY_PLUS_DETAIL VARCHAR2(100),
    MEMBER_E_MONEY_MINUS NUMBER(30) DEFAULT 0,
    MEMBER_E_MONEY_MINUS_DETAIL VARCHAR2(100),
    MEMBER_E_MONEY_UPDATE DATE DEFAULT SYSDATE,
    CONSTRAINT MONEY_MEMBER_E_MONEY_NO_PK PRIMARY KEY (MEMBER_E_MONEY_NO),
    CONSTRAINT MONEY_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)    
);

DROP SEQUENCE MEMBER_E_MONEY_NO_SEQ;

CREATE SEQUENCE MEMBER_E_MONEY_NO_SEQ
INCREMENT BY 1
START WITH 1;
    
