DROP TABLE MEMBER_E_MONEY;

CREATE TABLE MEMBER_E_MONEY(
    MEMBER_NO NUMBER(10),
    MEMBER_E_MONEY_NO NUMBER(10),
    MEMBER_E_MONEY_PLUS NUMBER(30) DEFAULT 0,
    MEMBER_E_MONEY_PLUS_DETAIL VARCHAR2(100),
    MEMBER_E_MONEY_MINUS NUMBER(30) DEFAULT 0,
    MEMBER_E_MONEY_MINUS_DETAIL VARCHAR2(100),
    MEMBER_E_MONEY_UPDATE DATE DEFAULT SYSDATE,
    CONSTRAINT MONEY_MEMBER_E_MONEY_NO_PK PRIMARY KEY (MEMBER_E_MONEY_NO),
    CONSTRAINT MONEY_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)    
);

DROP SEQUENCE MEMBER_E_MONEY_NO_SEQ;

CREATE SEQUENCE MEMBER_E_MONEY_NO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO MEMBER_E_MONEY(MEMBER_NO, MEMBER_E_MONEY_NO, MEMBER_E_MONEY_PLUS_DETAIL, MEMBER_E_MONEY_MINUS, MEMBER_E_MONEY_MINUS_DETAIL)
VALUES(2, MEMBER_E_MONEY_NO_SEQ.NEXTVAL, NULL, 1000, '수강신청');

INSERT INTO MEMBER_E_MONEY(MEMBER_NO, MEMBER_E_MONEY_NO, MEMBER_E_MONEY_PLUS, MEMBER_E_MONEY_PLUS_DETAIL, MEMBER_E_MONEY_MINUS_DETAIL)
VALUES(2, MEMBER_E_MONEY_NO_SEQ.NEXTVAL, 1000, '수강신청 취소', NULL);

SELECT M.MEMBER_NO
			  ,M.MEMBER_E_MONEY AS CURRENT_BALANCE
			  ,MONEY.MEMBER_E_MONEY_NO
			  ,MONEY.MEMBER_E_MONEY_PLUS
			  ,MONEY.MEMBER_E_MONEY_PLUS_DETAIL
			  ,MONEY.MEMBER_E_MONEY_MINUS
			  ,MONEY.MEMBER_E_MONEY_MINUS_DETAIL			  
			  ,MONEY.MEMBER_E_MONEY_UPDATE
		FROM MEMBER M
		LEFT JOIN MEMBER_E_MONEY MONEY ON M.MEMBER_NO = MONEY.MEMBER_NO
		WHERE M.MEMBER_NO = 2
		ORDER BY MONEY.MEMBER_E_MONEY_UPDATE DESC;	

COMMIT;
    
